import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { Navbar1 } from "@/components/ui/navbar-1";
import { ThemeProvider } from 'next-themes';


const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "ForgeAura",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${bricolage.variable} font-sans antialiased`}
        style={{ fontFamily: 'var(--font-bricolage), sans-serif' }}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar1 />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
